title: "こっとんうぃんど"
description: "『わたかぜコウ』のポートフォリオサイト。気まぐれに様々なイラストや作品を載せてます。"
short:
  description: "わたかぜコウのポートフォリオサイト"
author:
  account: 'kouwtkz'
  ename: 'Kou Watakaze'
  mail: 'kouwtkz@cottonwind.com'
  smail: 'kouwtkz🐏cottonwind.com'
  name: 'わたかぜコウ'
  since: 2017
  x:
    main: 'kouwtkz'
    v: 'kouwtkz_v'
manifest:
  path: "/manifest.json"
  background_color: "#c1d64c"
  display: "minimal-ui"

enableEmoji: true
enableRobotsTXT: true

menu:
  nav:
    - name: 'about'
      url: '/about/'
    - name: 'gallery'
      url: '/gallery/'
    - name: 'character'
      short: 'chara'
      url: '/character/'
    - name: 'sound'
      url: '/sound/'
    # - name: 'game'
    #   url: '/game/'
    - name: 'blog'
      url: '/blog/'
    - name: 'special'
      url: '/special/'
    - name: 'other'
      url: '/other/'
  sns:
    - name: '𝕏 (Twitter)'
      url: 'https://x.com/kouwtkz'
      mask: '/mask/sns/twitter.png'
    - name: 'youtube'
      url: 'https://www.youtube.com/@kouwtkz'
      mask: '/mask/sns/youtube.png'
    - name: 'pixiv'
      url: 'https://www.pixiv.net/users/5577703'
      mask: '/mask/sns/pixiv.png'
    - name: 'instagram'
      url: 'https://www.instagram.com/kouwtkz/'
      mask: '/mask/sns/instagram.png'
    - name: 'github'
      url: 'https://github.com/kouwtkz'
      mask: '/mask/sns/github.png'
    - name: 'MisskeyDesign'
      rel: 'me'
      title: 'Misskey design'
      url: 'https://misskey.design/@kouwtkz'
      mask: '/mask/sns/misskey_design.png'
      row: 2
    - name: 'Mascodon'
      rel: 'me'
      title: 'マスコどん'
      url: 'https://mascodon.jp/@kouwtkz'
      mask: '/mask/sns/wtkz_mascodon.png'
      row: 2
    - name: 'VTdon'
      rel: 'me'
      url: 'https://vtdon.com/@kouwtkz'
      mask: '/mask/sns/vtdon.png'
      row: 2
    - name: 'kouwtkz'
      title: 'わたかぜコウのプロフィール'
      url: '/about/kouwtkz'
      row: 2
