version: "3"

volumes:
  next:
  node_modules:

services:
  nextjs:
    build: .
    restart: always
    tty: true #ポートがなくても動くようにする
    volumes:
      - ../:/mysite-next:delegated
      - next:/mysite-next/out:cached
      - node_modules:/mysite-next/node_modules
      - ~/docker/default.ssh:/root/.ssh
      - ~/docker/next.vscode-server:/root/.vscode-server
    environment: # 環境変数
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true  # ホットリロード
      - MEDIA_HOST_CONTAINER=http://nginx # NGINXのURL
      - MEDIA_HOST_PATH=_media  # メディアのディレクトリ
    command: sh -c "npm run start || sh" # 実行コマンド
    
  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - 80:80
      - 3001:81
      - 3002:82
      - 3003:83
    volumes:
      - ../out:/var/www:cached
      - ../_media:/var/www/_media:cached
      - ./nginx:/etc/nginx/conf.d
